route:
  receiver: 'gmail-notifications'
  group_by: ['alertname']
  group_wait: 30s        # wait 30s to group related alerts together
  group_interval: 5m     # wait 5m before sending updates on the same alert
  repeat_interval: 4h    # re-send if alert is still firing after 4 hours

receivers:
  - name: 'gmail-notifications'
    email_configs:
      - to: "kyrollesraafat@gmail.com"
        from: "kyrollesraafat99@gmail.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "kyrollesraafat99@gmail.com"
        auth_password_file: /etc/alertmanager/auth_e.txt
        headers:
          subject: "Prometheus Mail Alerts"
        send_resolved: true